const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome'});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const page=await context.newPage();const errors=[];let mediaRequests=0;
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:8795')&&r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
  page.on('request',r=>{if(r.url().endsWith('.mp4'))mediaRequests++;});
  await page.goto('http://127.0.0.1:8795/?review=0');
  assert.equal(await page.locator('.comparison-frame').count(),9);
  assert.equal(await page.locator('.comparison-handle').count(),9);
  assert.equal(mediaRequests,0,'No video downloads before interaction');
  const rows=await page.locator('.application-preview').evaluateAll(ns=>ns.map(n=>{const f=n.querySelector('.comparison-frame').getBoundingClientRect(),t=n.querySelector('.application-copy').getBoundingClientRect();return {top:f.y,left:f.x,text:t.x,bottom:f.bottom};}));
  rows.forEach((r,i)=>{assert.ok(i%2?r.left>r.text:r.left<r.text);if(i)assert.ok(r.top>rows[i-1].bottom);});
  const card=page.locator('.application-preview').first(),frame=card.locator('.comparison-frame'),handle=card.locator('.comparison-handle'),transport=card.locator('.application-transport');
  await frame.scrollIntoViewIfNeeded();await page.mouse.move(0,0);
  assert.equal(await transport.evaluate(n=>getComputedStyle(n).opacity),'0');
  const box=await frame.boundingBox();
  const vids=await card.locator('video').evaluateAll(ns=>ns.map(n=>{const b=n.getBoundingClientRect();return [b.x,b.y,b.width,b.height];}));
  assert.deepEqual(vids[0],vids[1],'Video surfaces must coincide');
  await frame.hover();assert.equal(await transport.evaluate(n=>getComputedStyle(n).opacity),'1');
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*.76,box.y+box.height/2,{steps:12});await page.mouse.up();
  assert.ok(Number(await handle.getAttribute('aria-valuenow'))>65);
  const clip=await card.locator('figure').first().evaluate(n=>n.style.clipPath);assert.ok(clip.includes('polygon'));
  await handle.focus();await handle.press('Home');assert.equal(await handle.getAttribute('aria-valuenow'),'0');
  await handle.press('End');assert.equal(await handle.getAttribute('aria-valuenow'),'100');
  await handle.press('ArrowLeft');assert.equal(await handle.getAttribute('aria-valuenow'),'98');
  for(let i=0;i<24;i++)await handle.press('ArrowLeft');
  assert.equal(await handle.getAttribute('aria-valuenow'),'50');
  await card.locator('.application-play').click();
  await page.waitForFunction(()=>[...document.querySelector('.application-preview').querySelectorAll('video')].every(v=>v.currentTime>.2&&!v.paused),null,{timeout:65000});
  await card.locator('.application-sound').click();
  assert.deepEqual(await card.locator('video').evaluateAll(ns=>ns.map(v=>v.muted)),[true,false]);
  await card.locator('.application-play').click();
  assert.ok(await card.locator('video').evaluateAll(ns=>ns.every(v=>v.paused)));
  const reveal=await handle.getAttribute('aria-valuenow');
  const seekBox=await card.locator('.application-seek').boundingBox();
  await card.locator('.application-seek').click({position:{x:seekBox.width/2,y:seekBox.height/2}});
  await page.waitForFunction(()=>{const v=[...document.querySelector('.application-preview').querySelectorAll('video')];return v.every(x=>!x.seeking)&&Math.abs(v[0].currentTime-v[1].currentTime)<.08&&v[0].currentTime>1;});
  assert.equal(await handle.getAttribute('aria-valuenow'),reveal,'Timeline must not move divider');
  await page.goto('http://127.0.0.1:8795/?review=0');await page.mouse.move(0,0);
  await page.screenshot({path:path.resolve(__dirname,'../test-results/comparison-home.png'),fullPage:true});
  await page.locator('.application-preview').first().scrollIntoViewIfNeeded();await page.locator('.comparison-frame').first().hover();
  await page.locator('.application-preview').first().screenshot({path:path.resolve(__dirname,'../test-results/comparison-row.png')});
  await page.goto('http://127.0.0.1:8795/?review=1');await page.waitForFunction(()=>window.homeGalleryReady);
  assert.equal(await page.locator('.review-toolbar,.review-label').count(),0);
  assert.equal(await page.locator('.application-preview').first().getAttribute('data-case'),'astra-train');
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));
  await phone.goto('http://127.0.0.1:8795/?review=0');
  const mobileFrame=phone.locator('.comparison-frame').first();await mobileFrame.scrollIntoViewIfNeeded();
  await mobileFrame.tap({position:{x:30,y:35}});
  assert.ok(await mobileFrame.evaluate(n=>n.classList.contains('show-controls')));
  assert.equal(await mobileFrame.getAttribute('data-reveal'),'50','A tap reveals controls without changing comparison');
  assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const mobileRows=await phone.locator('.application-preview').evaluateAll(ns=>ns.map(n=>n.querySelector('.application-copy').getBoundingClientRect().top>=n.querySelector('.comparison-frame').getBoundingClientRect().bottom));
  assert.ok(mobileRows.every(Boolean));
  await phone.screenshot({path:path.resolve(__dirname,'../test-results/comparison-mobile.png')});
  const touch=await mobile.newCDPSession(phone),mb=await mobileFrame.boundingBox();
  const x=mb.x+mb.width/2,y=mb.y+mb.height/2;
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+75,y}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.ok(Number(await mobileFrame.getAttribute('data-reveal'))>60,'Horizontal touch drag changes split');
  const scrollBefore=await phone.evaluate(()=>scrollY);
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mb.x+35,y}]});
  for(const distance of [30,70,120])await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mb.x+35,y:y-distance}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await phone.waitForFunction(before=>scrollY>before+20,scrollBefore);
  await card.locator('h2 a').click();await page.waitForFunction(()=>window.homeGallery?.getState().state==='grid');
  assert.deepEqual(errors,[]);
  console.log('PASS: nine alternating rows, superimposed videos, diagonal drag/endpoints/keyboard, hover controls, playback/seek, output-only audio, review IDs, mobile tap/layout and Gallery links.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
