const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];let media=0;
  page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:8795')&&r.status()>=400)errors.push(r.url());});
  page.on('request',r=>{if(r.url().includes('.mp4'))media++;});
  const base='http://127.0.0.1:8795/';
  await page.goto(base+'?review=1');await page.waitForFunction(()=>window.homeGalleryReady);
  assert.equal(await page.locator('.review-toolbar,.review-label').count(),0);
  assert.equal(await page.locator('.category-shell').count(),10);assert.equal(await page.locator('.category-mosaic').count(),10);
  assert.equal(await page.locator('.category-shell .fps-case-bubble').count(),65);
  assert.equal(await page.locator('.application-preview').first().getAttribute('data-case'),'astra-train');
  assert.equal(await page.locator('#trajectory-variation .application-preview').getAttribute('data-case'),'577');
  assert.equal(await page.locator('.demo-load').textContent(),'Watch');assert.equal(media,0);
  const colors=await page.locator('.category-shell').evaluateAll(ns=>ns.map(n=>getComputedStyle(n).getPropertyValue('--atmosphere-a')));assert.ok(new Set(colors).size>6);
  await page.goto(base+'?review=0');await page.waitForFunction(()=>window.homeGalleryReady);await page.waitForTimeout(600);
  await page.screenshot({path:path.resolve(__dirname,'../test-results/integrated-home.png'),fullPage:true});
  const first=page.locator('#reconstruction-3d-4d'),next=page.locator('#long-horizon-style');
  const gapBefore=await next.evaluate(n=>n.offsetTop);
  await first.locator('.application-copy h2 a').click();
  await page.waitForFunction(()=>document.querySelector('#reconstruction-3d-4d').dataset.state==='grid');
  await page.waitForTimeout(700);
  assert.equal(new URL(page.url()).pathname,'/');assert.equal(await first.locator('.category-overview').isVisible(),false);
  assert.ok(await next.evaluate(n=>n.offsetTop)>gapBefore);
  await first.screenshot({path:path.resolve(__dirname,'../test-results/integrated-results.png')});
  await first.locator('.fps-case-bubble[data-case="442"]').click();
  await page.waitForFunction(()=>[...document.querySelectorAll('iframe')].some(f=>{try{return !!f.contentWindow.behindFrame;}catch{return false;}}),null,{timeout:90000});
  assert.equal(await first.getAttribute('data-state'),'detail');assert.equal(new URL(page.url()).pathname,'/');
  await first.locator('.fps-back').click();await page.waitForTimeout(650);
  assert.equal(await first.getAttribute('data-state'),'grid');assert.equal(await first.locator('iframe').count(),0);
  await first.locator('.category-collapse').first().click();await page.waitForTimeout(650);
  assert.equal(await first.getAttribute('data-state'),'overview');
  assert.ok(Math.abs(await next.evaluate(n=>n.offsetTop)-gapBefore)<3);
  await first.locator('.category-mosaic').click({position:{x:20,y:20}});await page.waitForTimeout(600);
  await next.locator('.application-copy h2 a').click();await page.waitForTimeout(700);
  assert.equal(await first.getAttribute('data-state'),'overview');assert.equal(await next.getAttribute('data-state'),'grid');
  assert.equal(await page.locator('.category-shell[data-state="grid"]').count(),1);
  await next.locator('.category-collapse').first().click();await page.waitForTimeout(650);
  await page.goto(base+'?review=1&category=trajectory-variation');await page.waitForFunction(()=>window.homeGalleryReady);
  assert.equal(await page.locator('#trajectory-variation').getAttribute('data-state'),'grid');
  assert.ok(await page.locator('#trajectory-variation .fps-case-bubble[data-case="577"]').count());
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.goto(base+'?review=0');await page.waitForFunction(()=>window.homeGalleryReady);await page.waitForTimeout(500);
  await page.screenshot({path:path.resolve(__dirname,'../test-results/integrated-mobile.png'),fullPage:true});
  await first.locator('.category-mosaic').click({position:{x:20,y:20}});await page.waitForTimeout(650);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await first.locator('.category-collapse').first().click();await page.waitForTimeout(600);
  assert.equal(await first.getAttribute('data-state'),'overview');
  assert.deepEqual(errors,[]);
  console.log('PASS: homepage highlights, Watch, category collages, shared result groups, inline expansion/pushdown, live detail/Return/overview, one open category, URL restoration, no review UI and mobile.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
