const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:8795/';await page.goto(base+'?review=0');await page.waitForFunction(()=>window.homeGalleryReady);
 const category=page.locator('#reconstruction-3d-4d'),card=category.locator('.application-preview');
 await card.locator('.comparison-frame').hover();await card.locator('.application-play').click();
 await page.waitForFunction(()=>document.querySelector('#reconstruction-3d-4d video').currentTime>.3,null,{timeout:65000});
 await card.locator('.comparison-handle').focus();await card.locator('.comparison-handle').press('End');
 await card.locator('h2 a').click();
 const times=await card.locator('video').evaluateAll(ns=>ns.map(v=>({time:v.currentTime,paused:v.paused})));assert.ok(times.every(v=>v.paused));
 await category.locator('.category-collapse').first().click();
 assert.equal(await card.locator('.comparison-handle').getAttribute('aria-valuenow'),'100');
 assert.deepEqual(await card.locator('video').evaluateAll(ns=>ns.map(v=>({time:v.currentTime,paused:v.paused}))),times);
 for(let i=0;i<5;i++)await page.evaluate(()=>{window.homeGallery.openCategory('long-horizon-style');window.homeGallery.collapseCategory();});
 assert.equal(await page.locator('.category-shell[data-state="grid"]').count(),0);
 await card.locator('h2 a').click();await category.locator('.fps-case-bubble[data-case="442"]').click();
 await category.locator('.category-collapse').first().click();await page.waitForTimeout(500);
 assert.equal(await category.getAttribute('data-state'),'overview');assert.equal(await page.locator('iframe').count(),0,'Closing an opening case must cancel its iframe');
 const selection='trajectory-group23-577-578-image-group23-2-v16';
 await page.goto(base+'?case=577&selection='+selection+'&review=1');await page.waitForFunction(()=>window.homeGalleryReady);
 await page.waitForFunction(()=>[...document.querySelectorAll('iframe')].some(f=>{try{return f.contentWindow.behindFrame?.getState().caseId==='577';}catch{return false;}}),null,{timeout:90000});
 const current=()=>page.evaluate(()=>[...document.querySelectorAll('iframe')].find(f=>f.contentWindow.behindFrame)?.contentWindow.behindFrame.getState());
 let state=await current();assert.equal(state.selectionId,selection);assert.equal(state.threejsSHA,'7120de68c82dfb598f995ba280cecf19bcc945b59280269ba18d60c937215053');
 await page.locator('#trajectory-variation .fps-variant[data-variant="b"]').click();
 await page.waitForFunction(()=>{const f=document.querySelector('#trajectory-variation iframe:not(.is-staged)');return f?.contentWindow.behindFrame?.getState().caseId==='578';},null,{timeout:90000});
 state=await current();assert.equal(state.selectionId,selection);assert.equal(state.threejsSHA,'2da6f461b2637565543a354f1f5f723c0a78b96fcc3255b623ed7c6e5de15322');
 await page.locator('#trajectory-variation .category-collapse').first().click();assert.equal(await page.locator('iframe').count(),0);assert.equal(new URL(page.url()).searchParams.has('case'),false);
 assert.deepEqual(errors,[]);console.log('PASS overview pause/time/reveal preservation, rapid toggles, R044 deep link/source revisions/A-B transition and iframe disposal.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
